@url = http://localhost:3000/api
@json = Content-Type: application/json


get {{url}}/


### all users
get {{url}}/users

### 注册
post {{url}}/register
{{json}}

{
    "username": "joshua5",
    "password": "1234"
}

### 登录post {{url}}/login
post {{url}}/login
{{json}}

{
    "username": "joshua1",
    "password": "1234"
}

### 个人信息
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDM3M2E3ODg1MzQxMDIyNjg3YTkyYTUiLCJpYXQiOjE2MTQyMzMwMzd9.WoJ3p8mwaeurpg7G68M_MC8hLj6ldkOEirA5MUkwLec
